#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Sep 03 12:31:07 PDT 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail
# simulate design
echo "xsim adc_c2h_bridge_tb_behav -key {Behavioral:sim_2:Functional:adc_c2h_bridge_tb} -tclbatch adc_c2h_bridge_tb.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/bd_f60c.protoinst" -protoinst "protoinst_files/bd_365d.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim adc_c2h_bridge_tb_behav -key {Behavioral:sim_2:Functional:adc_c2h_bridge_tb} -tclbatch adc_c2h_bridge_tb.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/bd_f60c.protoinst" -protoinst "protoinst_files/bd_365d.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

